name: Build LaTeX PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v2
      - name: Compile LaTeX document
        run: latexmk -pdf -interaction=nonstopmode resume.tex
      - name: Upload PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          force_orphan: true
